# Generated by Django 4.1.7 on 2023-03-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_options_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-created",),
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
